kind = "web"
previewPath = "/"
title = "Carômetro"
version = "1.0.0"
id = "artifacts/carometro"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24620

[services.development]
run = "pnpm --filter @workspace/carometro run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/carometro", "run", "build" ]
publicDir = "artifacts/carometro/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24620"
BASE_PATH = "/"
